### ISSUE TITLE
Allow multiple accounts configuration in config file

### ISSUE THREAD

**Issue by jormaechea** [jormaechea/vtex-order-placer#2]
Allow a property `accounts` in config file with the following structure:
```yaml
accounts:
  'accountName1':
    apiKey: 'the key'
    apiToken: 'the token'
  'accountName2':
    apiKey: 'the key'
    apiToken: 'the token'
```

Account selection should be able to be done by setting the account name in:
- CLI argument `--accountName`
- Config file property `accountName`
